apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "firefly-signer.fullname" . }}-config
  labels:
    {{- include "firefly-signer.labels" . | nindent 4 }}
data:
  config.yaml: |
    server:
      address: {{ .Values.signer.address }}
      port: {{ .Values.signer.port }}
    backend:
      url: {{ .Values.signer.backend.url }}
      chainId: {{ .Values.signer.backend.chainId }}
    fileWallet:
      enabled: true
      path: {{ .Values.signer.filestore.path }}
      {{- if .Values.signer.filestore.passwordFile }}
      defaultPasswordFile: {{ .Values.signer.filestore.passwordFile }}
      {{- end }}
