apiVersion: v1
kind: Service
metadata:
  name: {{ include "firefly-signer.fullname" . }}
  labels:
    {{- include "firefly-signer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "firefly-signer.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP

