apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "besu.fullname" . }}-genesis
  labels:
    {{- include "besu.labels" . | nindent 4 }}
data:
  genesis.json: {{ .Files.Get "genesis.json" | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "besu.fullname" . }}-validators
  labels:
    {{- include "besu.labels" . | nindent 4 }}
data:
  enodes.txt: {{ .Files.Get "enodes.txt" | quote }}
