apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "besu.fullname" . }}
  labels:
    {{- include "besu.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "besu.fullname" . }}
  labels:
    {{- include "besu.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "besu.fullname" . }}
  labels:
    {{- include "besu.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "besu.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "besu.fullname" . }}
  namespace: {{ .Release.Namespace }}